server:
   port: 8080
   
nacos:
  appId: fire-press.properties
  appStage: develop
  appVer: 1.0.0
#  ip: 139.9.50.212
  ip: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
  configType: properties

